### PR TITLE
MINOR: Add Josep Prat Key

### PR DESCRIPTION
**Pull request by jlprat**
Once merged, could a PMC member update the KEYS file in https://dist.apache.org/repos/dist/release/kafka/KEYS?

Thanks!

### CODE REVIEW

**Review by soarez — APPROVED** [review]
It looks like your key doesn't have the `CODE SIGNING KEY` comment. https://infra.apache.org/release-signing.html#key-comment

Otherwise LGTM

**Comment by jlprat** [comment]
I see that others also lack this comment? How important is it to have it?

**Comment by soarez** [comment]
I noticed the same. I don't know if it is actually important. I suppose you can add another key later if it proves really necessary.

**Comment by mimaison** [comment]
I added the key to https://dist.apache.org/repos/dist/release/kafka/KEYS

**Comment by jlprat** [comment]
Thanks @mimaison !

**Pull request merged**
