### PR TITLE
Fixes a 'Persistance' doc

### PR DESCRIPTION
**Pull request by IvanVas**
I think JBOD and RAID-5 are mutually exclusive, so there's probably a mistake here.

### CODE REVIEW

**Comment by mjsax** [comment]
@mimaison -- I have no context on this question. Do you? If not, who should we ping for review?

**Comment by IvanVas** [comment]
JBOD is a configuration where each drive in a storage array is treated as an independent disk. The system simply concatenates multiple drives, allowing them to appear as a single large disk to the operating system.
RAID is a storage technology merging two or more HDDs or SSDs into one cohesive storage unit or array.

**Review by soarez — APPROVED** [review]
I agree, the statement incorrectly conflates JBOD with RAID.

**Comment by mjsax** [comment]
@soarez Any reason why you did not merge this PR?

**Comment by soarez** [comment]
No, not really 👍 Thanks for the reminder @mjsax

**Pull request merged**
