### PR TITLE
Provide link to ZooKeeper within Quickstart

### PR DESCRIPTION
**Pull request by restlessdesign**
This adds a hyperlink to the ZooKeeper project within the quickstart tutorial for users who may be unfamiliar with ZooKeeper or who simply want a more-direct path to downloading the software.

### CODE REVIEW

**Comment by guozhangwang** [comment]
@restlessdesign thanks for the PR, could you submit the change on the kafka repo: https://github.com/apache/kafka/tree/trunk/docs

which will be reflected here when a release is published? We usually only make non-templated doc changes on this repo.

**Comment by guozhangwang** [comment]
See: https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Website+Documentation+Changes

**Comment by restlessdesign** [comment]
No problem!

**Comment by restlessdesign** [comment]
See: https://github.com/apache/kafka/pull/3372

**Pull request closed without merging**
