### PR TITLE
MINOR: Fix link to Connect OpenAPI spec

### PR DESCRIPTION
**Pull request by mimaison**

### CODE REVIEW

**Comment by mimaison** [comment]
cc @jsancio

**Review by jsancio — APPROVED** [review]
LGTM

**Comment by jsancio** [comment]
@mimaison, do we need to make a similar change to the `apache/kafka` repo?

**Comment by mimaison** [comment]
@jsancio Yes I opened https://github.com/apache/kafka/pull/12713

**Pull request merged**
