### PR TITLE
Add atguigu(http://www.atguigu.com/)to the list pf the "Powered By ❤"

### PR DESCRIPTION
**Pull request by realdengziqi**
Validated rendering and links by running Apache server locally. The entry renders like this:

atguigu

### CODE REVIEW

**Comment by realdengziqi** [comment]
@cadonna can you please review? Thanks♪(･ω･)ﾉ

**Comment by realdengziqi** [comment]
@PhilippB21  can you please review? Thank you♪(･ω･)ﾉ

**Comment by PhilippB21** [comment]
@realdengziqi Sorry, bur I am not authorized to do a review and so far I have only submitted our company logo.

**Review by guozhangwang — APPROVED** [review]
Thanks @realdengziqi , the PR lgtm.

**Pull request merged**
