### PR TITLE
MINOR: updated deprecated streams constants

### PR DESCRIPTION
**Pull request by londoncalling**
## Description

**Docs update: Streams Developer Guide**

- `KEY_SERDE_CLASS_CONFIG` and `VALUE_KEY_SERDE_CLASS_CONFIG` were deprecated in https://kafka.apache.org/11/javadoc/deprecated-list.html and replaced by `DEFAULT_KEY_SERDE_CLASS_CONFIG` and `DEFAULT_VALUE_KEY_SERDE_CLASS_CONFIG`

- Replaced deprecated constants in example code with up-to-date ones in `11` and all subsequent versions

## Related

PR on `apache/kafka`: https://github.com/apache/kafka/pull/6466

## cc, please review/merge:

- @joel-hamill, @JimGalasyn,  @guozhangwang 

Signed-off-by: Victoria Bialas <vicky@confluent.io>

### CODE REVIEW

**Review by JimGalasyn — APPROVED** [review]
LGTM

**Comment by mjsax** [comment]
Thanks for the PR @londoncalling! Both configs are deprecated since 0.11.0.0 release (compare https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=68714788) -- can we update 0.11 and 1.0, too in this PR? The mentioned KIP also deprecates `timestamp.extractor` in favor of `default.timestamp.extractor` -- would be good to include this in this PR, too.

**Comment by londoncalling** [comment]
@mjsax , on the most recent commit, I replaced `TIMESTAMP_EXTRACTOR_CLASS_CONFIG` with `DEFAULT_TIMESTAMP_EXTRACTOR_CLASS_CONFIG` in the code example for defining a custom timestamp extractor in Developer Guide topic on [Configuring a Streams Application](https://kafka.apache.org/documentation/streams/developer-guide/config-streams.html) on these versions:
- `10/streams/developer-guide/config-streams.html`
- `11/streams/developer-guide/config-streams.html`
- `20/streams/developer-guide/config-streams.html`
- `21/streams/developer-guide/config-streams.html`
- `22/streams/developer-guide/config-streams.html`

It looks like it's already covered in the generated Javadoc. Let me know if this fixes it, and feel free to merge if all looks good!

**Comment by mjsax** [comment]
Thanks a lot for the PR @londoncalling!

**Comment by mjsax** [comment]
Merged to `trunk` and cherry-picked to `2.2` and `2.1`. Cherry-picking to `2.0` resulted in conflicts.

Might be worth to do a new PR for `2.0` ?

**Pull request merged**
