### PR TITLE
MINOR: Add release dates to downloads page

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@ijuma @guozhangwang @junrao I think it'd be good to start including these to help indicate to users how old the releases they are downloading are.

**Comment by guozhangwang** [comment]
What about pre-0.8.2 releases?

**Comment by ewencp** [comment]
I can dig up the release dates, I just grabbed the ones that were readily available via the git history for this file (which, admittedly, might be slightly off). I'm happy to round them out via svn history and/or digging through mailing list history if people think it is worth it.

**Comment by ijuma** [comment]
Good idea. As you said, the dates seem to differ slightly from: https://issues.apache.org/jira/browse/KAFKA/?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel

It would be nice to get pre-0.8.2 dates since we're doing this.

**Comment by ewencp** [comment]
I grabbed the dates from that page and filled in the beta ones based on mailing list posts. The actual dates seem to be inconsistent and the JIRA release dates aren't always maintained (I know because I dug up dates and closed a few other releases when I last ran one), but tbh the point here is just the rough timing anyway.

**Review by ijuma — APPROVED** [review]
Thanks for posting all of the dates and updating JIRA too. Nice to be able to see it all in one place. LGTM. I will let you merge it.

**Pull request closed without merging**
