### PR TITLE
add Edoardo to committer list

### PR DESCRIPTION
**Pull request by edoardocomar**

### CODE REVIEW

**Comment by edoardocomar** [comment]
@mimaison @rajinisivaram 
I do not understand if I should squash and merge myself or ask for approval ...

**Review by mimaison — APPROVED** [review]
Congrats!

**Comment by mimaison** [comment]
Approvals are not compulsory on kafka-site but typically it's still always best to get someone to take a look and approve. I've approved now, so feel free to merge.

**Comment by edoardocomar** [comment]
> Approvals are not compulsory on kafka-site but typically it's still always best to get someone to take a look and approve. I've approved now, so feel free to merge.

Thanks !

**Pull request merged**
