### PR TITLE
adding spitha on powered-by

### PR DESCRIPTION
**Pull request by VictorParkM**
adding spitha on powered-by

### CODE REVIEW

**Comment by mjsax** [comment]
@VictorParkM -- happy to merge this, but it seems your web-page does not follow ASF guidelines with regard to respecting the Apache Kafka trademark.

- https://www.apache.org/foundation/marks/
- https://www.apache.org/foundation/marks/faq/#attribution

Could you address this issue on your side?

**Comment by mjsax** [comment]
@VictorParkM -- This PR need to be rebased; merged a couple of other PRs and there is merge conflicts now.

**Comment by VictorParkM** [comment]
Hi Matthias

Nice to e-meet you.

I don't fully understand what it means for a PR to be rebased. Should I
understand it as needing to merge it again with the latest version?

Also, we internally reviewed our website last week because it was said that
it does not comply with ASF guidelines. Could you please let me know if
this is due to the presence of the term "Apache Kafka" on our website, or
if there are other reasons?

Regards,

Victor Park.


JeongHun Park

Business Development / Team Manager

SPITHA INC.
43, Daesagwan-ro, Yongsan-gu, 04401
SEOUL, SOUTH KOREA
M) +82.010.4321.2320
E) ***@***.*** ***@***.***>

*spitha.io <http://spitha.io/>*



The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.


2024년 6월 22일 (토) 오전 4:49, Matthias J. Sax ***@***.***>님이 작성:

**Comment by mjsax** [comment]
> I don't fully understand what it means for a PR to be rebased. Should I
understand it as needing to merge it again with the latest version?

https://git-scm.com/book/en/v2/Git-Branching-Rebasing

I guess, merging lates `asf-site` into your PR should also work. Merging would basically put the new changes in `asf-site` after your own commits, while rebasing put the in front of it.

> Also, we internally reviewed our website last week because it was said that
it does not comply with ASF guidelines. Could you please let me know if
this is due to the presence of the term "Apache Kafka" on our website, or
if there are other reasons?

It's totally ok to mention "Apache Kafka" but you need to add the trademark signs as explained. So it should be `Apache Kafka®` not just `Apache Kafka`, and you should have something like `Apache Kafka, Kafka, and the Kafka logo are either registered trademarks or trademarks of The Apache Software Foundation in the United States and other countries.`  on the web-page, too.

**Comment by VictorParkM** [comment]
Thank you very much for the kind and detailed advice. 
I sent the request again: https://github.com/apache/kafka-site/pull/611

About ASF guidelines, I will share the issue with the team to fix it as soon as possible. 
Thank you.

**Comment by mjsax** [comment]
Thanks for the new PR. Left a comment there. Closing this.

> About ASF guidelines, I will share the issue with the team to fix it as soon as possible.

Thanks. Let us know after you applied the change to the webpage, or if you have any question about it private@kafka.apache.org

**Comment by VictorParkM** [comment]
I have updated the homepage(www.spitha.io) following the ASF guidelines.

 If you clear your browser's cache, you can check the updated homepage.

Thank you



JeongHun Park

Business Development / Team Manager

SPITHA INC.
43, Daesagwan-ro, Yongsan-gu, 04401
SEOUL, SOUTH KOREA
M) +82.010.4321.2320
E) ***@***.*** ***@***.***>

*spitha.io <http://spitha.io/>*



The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.


2024년 6월 26일 (수) 오전 9:29, Matthias J. Sax ***@***.***>님이 작성:

**Pull request closed without merging**
