### PR TITLE
MINOR: update download links

### PR DESCRIPTION
**Pull request by mjsax**
- https://www.apache.org/legal/release-policy.html#release-announcements
- https://infra.apache.org/release-download-pages.html

### CODE REVIEW

**Review by jlprat — APPROVED** [review]
LGTM! Thanks @mjsax 
At first I though you missed all checksums and signature links but then I realize that infra specifies that those should be pointing to `downloads`:
> All links to checksums, detached signatures and public keys must reference the Apache Distribution Directory ([downloads.apache.org](https://downloads.apache.org/)) and use https:// (SSL). For example: https://downloads.apache.org/httpd/KEYS.

**Comment by mjsax** [comment]
Yes, I am just not sure what to do with the release notes? I did reply on the dev mailing list to Craig Russell and hope he can clarify.

**Comment by jlprat** [comment]
My guess would be just binaries/sources only because of the volume, but this is just my educated guess.

**Comment by clr-apache** [comment]
Yes, the changes from downloads to dlcdn are correct. The release notes should also refer to dlcdn as well. The reason for using downloads is to make sure that the small checksums and signatures are not intercepted. But the larger artifacts need to be load balanced by using dlcdn.
Thanks for taking care of this.

**Comment by mjsax** [comment]
Thanks @clr-apache -- pushed an update to this PR.

Also added a few more improvements \cc @jlprat

**Review by jlprat — APPROVED** [review]
LGTM! Thanks! And good thing to add the comments for future versions to remember to use the right domains for each type of file

**Pull request merged**
