### PR TITLE
Update ZK migration section to indicate GA

### PR DESCRIPTION
**Pull request by mumrah**
Also fix a few other small nitpicks I noticed

### CODE REVIEW

**Review by satishd — COMMENTED** [review]
Thanks @mumrah for raising the PR for adding updates on ZK -> KRaft migration. 

I raised https://github.com/apache/kafka-site/pull/547 for a blog section. You can rebase this PR on #547. We can merge it only when the release is finalized and other updates are done as you suggested [here](https://github.com/apache/kafka-site/pull/542#issuecomment-1723818513).

**Comment by mjsax** [comment]
@mumrah -- Any updates on this PR?

**Comment by mumrah** [comment]
Just updated this with relevant notes for 3.6.0

**Review by satishd — APPROVED** [review]
Thanks @mumrah foe the PR. LGTM.

**Pull request merged**
