### PR TITLE
MINOR: Add placeholder images that will load iframe. 

### PR DESCRIPTION
**Pull request by bbejeck**
This PR is a follow-up from #430 and https://github.com/apache/kafka-site/pull/427. This PR adds a clickable image that will load an iframe for each one of the Kafka Streams videos. This aligns with the [ASF privacy policy](https://privacy.apache.org/faq/committers.html) on embedded YouTube videos. 

Some screenshots are included, but for reviewing, it's suggested to render this PR locally

Screen Shot 2022-08-04 at 11 15 27 AM

Screen Shot 2022-08-04 at 11 15 38 AM

Screen Shot 2022-08-04 at 11 15 47 AM

Screen Shot 2022-08-04 at 11 15 56 AM

Screen Shot 2022-08-04 at 11 16 04 AM

Screen Shot 2022-08-04 at 11 16 16 AM

### CODE REVIEW

**Comment by bbejeck** [comment]
Ping @vvcephei @mimaison @divijvaidya for review.

Once this PR is approved, I'll do a mirror PR for the Apache Kafka repo

**Review by divijvaidya — APPROVED** [review]
Thank you for making the changes. Looks good to me!

**Comment by mimaison** [comment]
It does not seem to render quite right for me.

The first video is fine:
image

But then for the 3 other ones the text is on the side:
image

The "play" icon is not centered on some of the images, for example `transforming_part_1-iframe-placeholder.png`:
image


Also should we bring back the previous layout (for example at a70c99b2a9b4a06473b60c38961042374b7a1c20) ? where the list of video names was on the right:
image

**Comment by bbejeck** [comment]
@mimaison, I've addressed your comments - thanks for the review I think it's important to get back the original look and feel

**Comment by mimaison** [comment]
Thanks @bbejeck !
I think the placeholder images could be improved a bit more. They are pretty low resolution, not quite the same size and the play icon is not centered on some of them.

ezgif-4-20686390df

That said these are small issues we can fix later so I'll approve.

**Review by mimaison — APPROVED** [review]

**Comment by bbejeck** [comment]
Thanks @mimaison I'll do a follow-up PR soon to try and get those cleaned up a bit

**Pull request merged**
