### PR TITLE
MINOR: Add 3.8.1 to upgrade for 3.9 docs. Also aadd rolling upgrade …nstructions

### PR DESCRIPTION
**Pull request by jlprat**

### CODE REVIEW

**Comment by showuon** [comment]
@jlprat , for 3.8.1's section, I've added in this PR: https://github.com/apache/kafka-site/pull/642 . Please take a look first. Thanks.

**Review by showuon — APPROVED** [review]

**Comment by jlprat** [comment]
My PR is not needed then. By the title of it I didn't think it included this change. My bad!

**Comment by jlprat** [comment]
We can take yours and add anything missing in there

**Comment by showuon** [comment]
But I didn't include the 3.9.0 upgrade guide as in your PR. My thought is to merge my PR first, and then merge yours. WDYT?

**Comment by jlprat** [comment]
Let's do it. Yours is approved already

**Comment by jlprat** [comment]
I'll reopen the PR something is strange in this one.

**Pull request closed without merging**
