### PR TITLE
MINOR: removing docs version header from 2.6 docs

### PR DESCRIPTION
**Pull request by scott-confluent**
Also re-adding it to the 2.5 docs

### CODE REVIEW

**Comment by ableegoldman** [comment]
Should this header be on all the earlier versions too? I don't see it anywhere at the moment (except for 2.6)

**Comment by rhauch** [comment]
@ableegoldman I see the header on 2.4 and earlier. IIUC, this is to *add* this header to the 2.5 docs and *remove* this header from all of the 2.6 docs (e.g., https://kafka.apache.org/26/documentation/streams/developer-guide/).

**Review by rhauch — APPROVED** [review]
LGTM. Thanks, @scott-confluent!

**Comment by ableegoldman** [comment]
Huh, I don't see the header on 2.4 (or earlier). Since this has been merged I now only see it on 2.5

**Comment by ableegoldman** [comment]
Just tried in a different browser and I still only see the header on 2.5. The 2.4 formatting looks a little different, but no "You're viewing an older version..." header

**Pull request merged**
