### PR TITLE
MINOR: Default to 3.5 docs

### PR DESCRIPTION
**Pull request by mimaison**

### CODE REVIEW

**Review by jlprat — COMMENTED** [review]
Hi @mimaison. Do you plan to do another PR with the update to the `downloads.html` page that would include the new release links?

**Comment by mimaison** [comment]
Sorry @jlprat I was still making changes I should have kept the PR in draft mode. I think I've done all the necessary changes now.

It looks like we missed a bunch of updates when we released 3.4 as the 3.3 docs don't display the `You're viewing documentation for an older version of Kafka` banner.

**Review by jlprat — APPROVED** [review]
Thanks @mimaison ! LGTM

**Review by jlprat — APPROVED** [review]
LGTM Thanks @mimaison !

**Pull request merged**
