### PR TITLE
MINOR: Updates for 3.0.1

### PR DESCRIPTION
**Pull request by mimaison**
Waiting for the artifacts to appear in Maven/Apache Mirrors

### CODE REVIEW

**Comment by mimaison** [comment]
Artifacts are available:
- https://archive.apache.org/dist/kafka/3.0.1/
- https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.0.1/

Ready for review

**Comment by mimaison** [comment]
cc @dajac @tombentley

**Review by ijuma — APPROVED** [review]
LGTM, thanks!

**Review by tombentley — APPROVED** [review]

**Comment by dajac** [comment]
@mimaison Could we also update the doc in the main repo? Otherwise we might lose the updates in the next minor release.

**Comment by mimaison** [comment]
@dajac I opened https://github.com/apache/kafka/pull/11906
I believe it's the only change that can be applied to `kafka/trunk`

**Pull request merged**
