### PR TITLE
Netstratum info updated

### PR DESCRIPTION
**Pull request by netstratum-labs**
Added Netstratum information and how we use Kafka in our products.

### CODE REVIEW

**Comment by mjsax** [comment]
@netstratum-labs -- can you rebase this PR to resolve merge conflicts?

**Comment by netstratum-labs** [comment]
rebase completed. Should I need to request a new PR?

**Comment by netstratum-labs** [comment]
@mjsax 

rebase completed. Should I need to request a new PR?

Tx

**Comment by mjsax** [comment]
@netstratum-labs -- The rebase seems not to be correct -- the PR shows many more changes that it should. If it's easier for you, you can also just do a new PR instead.

**Pull request closed without merging**
