### PR TITLE
Typo in kafka 0.10.2 topics operation doc

### PR DESCRIPTION
**Pull request by jlisam**
I believe it should be "not" and not "noi"

### CODE REVIEW

**Comment by gwenshap** [comment]
Sorry, documentation changes actually don't go here... they go in the source repo and are pushed here.
See the instructions here: https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Website+Documentation+Changes

**Comment by jlisam** [comment]
I see. No worries. I will make the changes in the right place

**Comment by ewencp** [comment]
@jlisam Could you close out this PR since the changes were retargeted to the main Kafka repo?

**Comment by jlisam** [comment]
sure thing

**Pull request closed without merging**
