### PR TITLE
KAFKA-13868: Replace embedded YouTube links with hyperlinks on streams page

### PR DESCRIPTION
**Pull request by divijvaidya**
This is a hot fix to merge the https://github.com/apache/kafka/pull/12438 into kafka-site to satisfy the ASF privacy policy requirements. 

## Testing
Tested locally.
Screenshot 2022-07-27 at 14 46 06

### CODE REVIEW

**Comment by divijvaidya** [comment]
@mimaison please review. Last one before we can close KAFKA-13868.

**Review by showuon — APPROVED** [review]
I confirmed the change is the same as the one in https://github.com/apache/kafka/pull/12438 . Thanks for the fix!

**Comment by showuon** [comment]
@mimaison , do you want to have another look?

**Review by mimaison — APPROVED** [review]
Tested locally, LGTM

**Pull request merged**
