### PR TITLE
MINOR Add Satish as a committer

### PR DESCRIPTION
**Pull request by satishd**
MINOR Add Satish as a committer

### CODE REVIEW

**Review by jlprat — APPROVED** [review]
LGTM

**Comment by jlprat** [comment]
Congrats again!

**Review by showuon — APPROVED** [review]
congratulation @satishd ! You can merge this PR now. Let me know if you encounter any problem. :)

**Review by jolshan — APPROVED** [review]

**Comment by satishd** [comment]
Thank you all.

**Pull request merged**
