### PR TITLE
KAFKA-18047: Add org.apache.kafka.automatic.config.providers to System Properties section

### PR DESCRIPTION
**Pull request by frankvicky**
JIRA: [KAFKA-18047](https://issues.apache.org/jira/browse/KAFKA-18047)

Add documentation of `org.apache.kafka.automatic.config.providers` to System Properties section.

### CODE REVIEW

**Comment by frankvicky** [comment]
Hi @mimaison 
I also file the patch for 3.8 and 3.9. 
PTAL 🙇🏼

**Comment by mimaison** [comment]
Let me see if this is a clean backport. If so, no need to open new PRs, I can just cherry pick this onto the other branches. I'll let you know if I need anything.

**Review by mimaison — APPROVED** [review]
LGTM

**Comment by mimaison** [comment]
Port of https://github.com/apache/kafka/pull/17920

**Pull request merged**
