### PR TITLE
Add chia7712 to committers

### PR DESCRIPTION
**Pull request by chia7712**
hello Kafka :)

### CODE REVIEW

**Comment by guozhangwang** [comment]
@chia7712 you'd also need to `git add` the image file as well.

**Comment by guozhangwang** [comment]
otherwise, LGTM!

**Comment by chia7712** [comment]
@guozhangwang thanks for reviews!

> you'd also need to git add the image file as well.

The image file is already included. Please correct me if I misunderstand your point.

**Comment by guozhangwang** [comment]
I missed that file. You are good to go.

**Comment by chia7712** [comment]
@guozhangwang Thanks for confirming. Merge it to trunk :)

**Pull request merged**
