### PR TITLE
Remove mention of Twitter as a way to get added to "Powered By"

### PR DESCRIPTION
**Pull request by ijuma**
The mailing list seems more suitable.

### CODE REVIEW

**Comment by ijuma** [comment]
Maybe we should ask people to submit a PR to this repo directly instead of the mailing list. What do you think @guozhangwang?

**Comment by guozhangwang** [comment]
Yeah I think encouraging people to directly submit PRs is better.

**Comment by guozhangwang** [comment]
Anyways, this change LGTM. Please feel free to merge afterwards

**Comment by ijuma** [comment]
@guozhangwang I updated the PR to mention pull request first.

**Pull request merged**
