### PR TITLE
KAFKA-9423: Refine layout of configuration options on website and make individual settings directly linkable

### PR DESCRIPTION
**Pull request by soenkeliebau**
This pull request goes together with https://github.com/apache/kafka/pull/7955 to achieve the desired effect.

### CODE REVIEW

**Review by mimaison — CHANGES_REQUESTED** [review]
Thanks. This can be simplifief a little bit.
The following should render exactly the same:
```
.config-list h4 {
    margin: 0;
}

.config-list table * {
    border: 0;
    background-color: transparent;
    padding: 0;
}

.config-list th {
    text-align: right;
}

.config-list td {
    text-align: left;
    padding: 0px 0px 0px 10px;
}
```

**Comment by soenkeliebau** [comment]
Hi @mimaison , made the changes and had a look at the generated page, looked good to me.
Nicely proves my point that I have no idea what I am doing with CSS :)

**Review by mimaison — APPROVED** [review]
LGTM

**Comment by mimaison** [comment]
I've also checked how the current docs render with the new CSS and it looks good.

**Pull request merged**
