### PR TITLE
Updated docs nav and docs toc

### PR DESCRIPTION
**Pull request by derrickdoo**
- Updated sub nav under docs navigation to display Streams and Connect below APIs
- Removed old links to Streams docs that are no longer relevant from table of contents

### CODE REVIEW

**Comment by derrickdoo** [comment]
@guozhangwang cc @miguno

**Comment by miguno** [comment]
LGTM

**Comment by guozhangwang** [comment]
LGTM. @derrickdoo could you have a separate PR for the `toc.html` changes in `kafka` repo as well?

**Comment by guozhangwang** [comment]
Merged to `asf-site`.

**Pull request closed without merging**
