### PR TITLE
MINOR Updated 3.6 javadocs by replacing 3.6.0-SNAPSHOT with 3.6.0

### PR DESCRIPTION
**Pull request by satishd**

### CODE REVIEW

**Review by showuon — APPROVED** [review]

**Comment by satishd** [comment]
cc @C0urante

**Comment by C0urante** [comment]
@satishd how were these files produced? It seems like the contents of the `36/javadoc` directory in this PR differ from the ones for the release candidate in https://home.apache.org/~satishd/kafka-3.6.0-rc2/javadoc/.

**Comment by satishd** [comment]
>@satishd how were these files produced? It seems like the contents of the 36/javadoc directory in this PR differ from the ones for the release candidate in https://home.apache.org/~satishd/kafka-3.6.0-rc2/javadoc/.

@C0urante Good catch! These files are generated from kafka repo on `3.6.0-rc2` tag with `aggregatedJavadoc` target with the default java version. But it seems files in https://home.apache.org/~satishd/kafka-3.6.0-rc2/javadoc/ are generated from jdk17 by `release.py`. Wiki does not mention that we need to use jdk17 for generating javadoc for kafka-site. 

Updated this PR by copying the javadoc files generated from kafka repo on `3.6.0-rc2` tag with `aggregatedJavadoc` target with jdk_17.  Please take a look and let me know if anything missing here. I will also update the wiki to use jdk17 for generating javadocs for kafka-site.

**Review by C0urante — APPROVED** [review]
LGTM, thanks Satish!

**Pull request merged**
