### PR TITLE
Migrate Streams Dev Guide content to AK

### PR DESCRIPTION
**Pull request by joel-hamill**
See related https://github.com/apache/kafka/pull/4252

### CODE REVIEW

**Comment by joel-hamill** [comment]
ping @guozhangwang

**Comment by derrickdoo** [comment]
@joel-hamill just took a look at your branch. Content looks good, but I'd suggest adding that horizontal subnav on the developer guide page for consistency and make sure users can easily jump around.

Here's the page I'm looking at:
image

**Comment by derrickdoo** [comment]
👍 💯 LGTM

**Comment by guozhangwang** [comment]
LGTM. Merged to asf-site.

**Pull request closed without merging**
