### PR TITLE
Fix errored json filename: expand-cluster-reassignment.json → custom-reassignment.json

### PR DESCRIPTION
**Pull request by dongjinleekr**
The description does not match the example command; Compare with other cases with `expand-cluster-reassignment.json` or `increase-replication-factor.json`.

### CODE REVIEW

**Comment by guozhangwang** [comment]
Thanks @dongjinleekr , what about other versions? (e.g. it seems 23 also have this issue) and can you also file a PR for kafka repo as well?

cc @omkreddy for another look since your name is the one suggested by github (so I trust their recommendation ranking algorithm :).

**Comment by omkreddy** [comment]
@dongjinleekr Thanks for the PR. LGTM. +1 to @guozhangwang comments. (update docs for  any other versions and . raise PR to update docs under Kafka repo)

**Comment by dongjinleekr** [comment]
Here it is; fix for the omitted 23 documentation.

I also opened a PR to the original Kafka repo. 😉

**Comment by dongjinleekr** [comment]
@omkreddy Here it is; fix for the omitted 23 documentation.

I also opened a PR to the original Kafka repo. 😉

**Review by omkreddy — APPROVED** [review]
LGTM

**Pull request merged**
