### PR TITLE
MINOR: update download links

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by guozhangwang** [comment]
What's the intention of using `https`, and why changing to `https://archive.apache.org`?

**Comment by mjsax** [comment]
`https` should always be the default IMHO (cf https://issues.apache.org/jira/browse/KAFKA-6222). For the link change compare: https://issues.apache.org/jira/browse/KAFKA-6223

**Comment by guozhangwang** [comment]
> https should always be the default IMHO (cf https://issues.apache.org/jira/browse/KAFKA-6222). For the link change compare: https://issues.apache.org/jira/browse/KAFKA-6223

ack.

**Review by guozhangwang — APPROVED** [review]

**Comment by lindong28** [comment]
LGTM. Verified that this patch only achieves the links for non-latest versions.

**Review by lindong28 — APPROVED** [review]

**Pull request merged**
