### PR TITLE
Add p3r (https://www.p3r.one/) to the list of the "Powered By ❤️"

### PR DESCRIPTION
**Pull request by hrittikhere**
[p3r](https://www.p3r.one/) uses Kafka as part of our Kubernetes Platform. We deliver it alongside Linkerd for development teams building event-based microservices. 

@hachikuji could you help merge this? (Noticed you helped the last traveller to these parts :) )

Feel free to contact me with any further questions.

### CODE REVIEW

**Comment by hrittikhere** [comment]
@devsayanta

**Comment by hrittikhere** [comment]
@rhauch can you please give this a look? Thanks :)

**Comment by hrittikhere** [comment]
@cadonna can you please review?

**Comment by cadonna** [comment]
Thank you for the PR @hrittikhere!

Did you test your changes with a local Apache server similar to [here](https://github.com/apache/kafka-site/pull/367#issuecomment-904755667) ?
Useful instructions can be found [here](https://cwiki.apache.org/confluence/display/KAFKA/Setup+Kafka+Website+on+Local+Apache+Server).

**Comment by cadonna** [comment]
ping @miguno

**Comment by hrittikhere** [comment]
I'm having few issues with local tests not sure why. But, will update you if I figure that out @cadonna

**Pull request closed without merging**
