### PR TITLE
Update Bruno's picture

### PR DESCRIPTION
**Pull request by cadonna**

### CODE REVIEW

**Review by divijvaidya — COMMENTED** [review]
I dig the new look! Very cool :) 

Is the dimension correct though? The new picture is tiny.

**Review by showuon — APPROVED** [review]
Yes, I agree the new pic is smaller, but it should be fine if you don't mind.

**Comment by cadonna** [comment]
Thanks! I looked at the pic in a browser and it looked fine.

**Comment by cadonna** [comment]
Sorry, I forgot to add the both of you as reviewers to the commit. 😞

**Comment by C0urante** [comment]
I was wondering who that bearded gentleman was at Kafka Summit!

**Pull request merged**
