### PR TITLE
Update the website repo link in code.html to point to github.

### PR DESCRIPTION
**Pull request by becketqin**

### CODE REVIEW

**Comment by ijuma** [comment]
Good catch, you probably want to include that link to that Apache Git repo as well.

**Comment by becketqin** [comment]
@ijuma The github site has stated that it is mirrored from the Apache repo. I added the link anyways.

**Comment by ijuma** [comment]
@becketqin, it's just that we point to the Apache git repo (which is the source repository) a few lines above for the code repo. We should probably be consistent and mention GitHub for both if we think that's useful. And we should probably point to the Apache one first (since it's the source repository) and mention the GitHub mirror second.

Finally, contributing documentation changes is a little different and there's a separate section for it in: http://kafka.apache.org/contributing.html

**Comment by becketqin** [comment]
@ijuma That's fair. I updated the page. The thing I found confusing is that we have documentation in three places: 1) Kafka code repo 2) kafka-site repo 3) some documentation are just a wiki page. I'll update https://cwiki.apache.org/confluence/display/KAFKA/Contributing+Website+Documentation+Changes to clarify this a little.

**Comment by becketqin** [comment]
@ijuma Does the updated page look good to you?

**Comment by ijuma** [comment]
LGTM, thanks.

**Comment by becketqin** [comment]
@ijuma Thanks for the review. Merged to the asf-site.

**Pull request merged**
