### PR TITLE
Fix typo - Acls Examples, Adding or removing a principal as producer …

### PR DESCRIPTION
**Pull request by sunnykrGupta**
…or consumer

### CODE REVIEW

**Comment by omkreddy** [comment]
LGTM

**Comment by ijuma** [comment]
Thanks for the PR, can you do a PR to the code repo https://github.com/apache/kafka/tree/trunk/docs?

**Comment by sunnykrGupta** [comment]
Sure. Did PR https://github.com/apache/kafka/pull/2839 . :)

**Comment by guozhangwang** [comment]
@sunnykrGupta Could you close this PR as 2389 on the kafka repo has been merged? I will be reflected in the kafka-site repo in the next major release.

**Comment by sunnykrGupta** [comment]
Great. Closing now.

**Pull request closed without merging**
