### PR TITLE
MINOR: Fix typo in MirrorMaker v2 documentation 

### PR DESCRIPTION
**Pull request by AdilHoumadi**
Fix typo in code example - s/enable/enabled

### CODE REVIEW

**Comment by mjsax** [comment]
@mimaison Can you review and merge this?

**Review by mimaison — APPROVED** [review]
Thanks for the PR, LGTM

**Comment by mimaison** [comment]
@AdilHoumadi Can you also open a PR to fix it in https://github.com/apache/kafka ? 
It's this file: https://github.com/apache/kafka/blob/trunk/docs/ops.html
Thanks

**Comment by AdilHoumadi** [comment]
@mimaison, sure!

**Pull request merged**
