### PR TITLE
MINOR: Update stream documentation for version 2.5

### PR DESCRIPTION
**Pull request by showuon**
1. fix broken links
2. rephrase a sentence
3. update the version number

### CODE REVIEW

**Comment by showuon** [comment]
Same change with the PR to `kafka` repo: https://github.com/apache/kafka/pull/8622/  per @bbejeck 's request. Thanks. :)

**Review by bbejeck — APPROVED** [review]
LGTM.

Verified by running asf-site locally.

**Comment by bbejeck** [comment]
Thanks for the contribution @showuon!

**Comment by bbejeck** [comment]
merged #265 into asf-site

**Pull request merged**
