### PR TITLE
KAFKA-14995: Automate asf.yaml collaborators refresh

### PR DESCRIPTION
**Pull request by stevenbooke**
Add Kafka Committers github login to be used for automating the refresh of Kafka collaborators.

### CODE REVIEW

**Comment by mimaison** [comment]
Let's sort out https://github.com/apache/kafka/pull/13842 first but this will need to be updated to include our new committer.

**Comment by stevenbooke** [comment]
Who is the new Committer? What is their Github username?

**Comment by mimaison** [comment]
The latest committer is Divij Vaidya, see at the bottom of https://kafka.apache.org/committers.
His Github username is `divijvaidya`.

**Comment by stevenbooke** [comment]
Ok, I will make the change now.

**Comment by stevenbooke** [comment]
@mimaison Could you review this and merge if there is no issues please?

**Comment by mimaison** [comment]
@stevenbooke Your branch has conflicts with `asf-site`. Can you resolve them? Thanks

**Comment by stevenbooke** [comment]
@mimaison Resolved merge conflicts.

**Comment by mimaison** [comment]
Thanks for the updates. I rendered the website with this change and realized the Github usernames are displayed. Can we hide them to keep the same display as today?

**Comment by stevenbooke** [comment]
@mimaison I have hidden the GitHub usernames of the kafka committers, they do not get displayed when the website is rendered. The display is now the same as today.

**Review by mimaison — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
