### PR TITLE
KAFKA-8209: Fix broken link for streams DSL page

### PR DESCRIPTION
**Pull request by bbejeck**
Fix link to point to dsl-api.html

### CODE REVIEW

**Comment by bbejeck** [comment]
\cc @MichaelDrogalis

**Comment by MichaelDrogalis** [comment]
LGTM.

**Review by mjsax — APPROVED** [review]
I there a PR for AK, too?

**Comment by mjsax** [comment]
Never mind. Found it: https://github.com/apache/kafka/pull/6564

**Comment by bbejeck** [comment]
\cc @JimGalasyn

**Comment by JimGalasyn** [comment]
cc @londoncalling

**Review by londoncalling — APPROVED** [review]
LGTM!

**Comment by bbejeck** [comment]
Merged #198 into asf-site

**Pull request merged**
