### PR TITLE
KAFKA-7315: Update internal links

### PR DESCRIPTION
**Pull request by ouertani**
Fix for https://issues.apache.org/jira/browse/KAFKA-7315

### CODE REVIEW

**Review by OneCricketeer — COMMENTED** [review]
minor: That section points at the 1.0 branch of the code rather than the same branch, or trunk

Not sure if that's intentional

**Comment by mjsax** [comment]
Version 2.0, 1.1, and 1.0 are affected too. Can you fix all of them?

**Comment by mjsax** [comment]
@ouertani Did you see my last comment?

**Comment by mjsax** [comment]
@ouertani Any updates on this PR?

**Comment by mjsax** [comment]
@ouertani Are you still interested to add the fix to the other versions?

**Comment by mjsax** [comment]
@londoncalling This PR is incomplete. Could you do a follow up PR if we merge this as-is? Just let us know. Thanks a lot!

**Comment by londoncalling** [comment]
@mjsax I can add the same fix to Version 2.0, 1.1, and 1.0 if you want to go ahead and merge the PR for @ouertani

**Comment by mjsax** [comment]
@londoncalling That would be cool. Note, that with `2.2` being release this would also need a fix. And we need a PR agains https://github.com/apache/kafka `trunk` to not reintroduce this bug later.

**Comment by londoncalling** [comment]
@mjsax should I wait until this PR has been merged?

**Comment by mjsax** [comment]
@londoncalling @ouertani -- Just cycling back to this -- I lost the overview --what is the status of this PR?

**Comment by londoncalling** [comment]
Matthias,
I was waiting for you to merge this .. then I was going to go back and
update the other branches.

Vicky

**Comment by mjsax** [comment]
Ah. Thanks @londoncalling -- and sorry for the long delay. Merged.

**Comment by mjsax** [comment]
Thanks for the fix @ouertani!

**Pull request merged**
