### PR TITLE
MINOR: Fix typo in title

### PR DESCRIPTION
**Pull request by joel-hamill**

### CODE REVIEW

**Comment by joel-hamill** [comment]
ping @guozhangwang

**Comment by guozhangwang** [comment]
Could you submit a patch to `kafka` repo under `docs/streams/index.html` as well?

**Comment by guozhangwang** [comment]
LGTM. Merged to `asf-site`.

**Comment by joel-hamill** [comment]
@guozhangwang done https://github.com/apache/kafka/pull/4133

**Pull request closed without merging**
