### PR TITLE
MINOR - Adding anchor links to download page

### PR DESCRIPTION
**Pull request by manjuapu**
Robin, can you please review this?

### CODE REVIEW

**Comment by guozhangwang** [comment]
> Robin, can you please review this?

@manjuapu if you do not ping Robin using his github id it will not work.

**Comment by manjuapu** [comment]
@guozhangwang  I know usually I comment here and include the PR in JIRA ticket. The reason I did that was Robin's github id doesn't show up here when I try to tag him.  Next time I will include the PR here, so that you are in sync about the PR status.
https://confluentinc.atlassian.net/browse/WEBR-200

**Comment by rmoff** [comment]
@manjuapu : My github is @rmoff :) 

The changes LGTM. Will the anchor hover-icons show up when hovering over each anchor (like it does here https://docs.confluent.io/current/)?

**Comment by manjuapu** [comment]
@rmoff  I have added anchor icon now. Can you please review this? Thanks!!

**Comment by manjuapu** [comment]
@guozhangwang  @rmoff has approved the functionality. Do you want any other approval for merging?

**Comment by guozhangwang** [comment]
LGTM.

@manjuapu could you also update the `kafka` repo, because otherwise once 1.1.0 or 1.0.1 is released these changes will be overridden again.

**Pull request merged**
