### PR TITLE
Add Qudosoft to powered-by

### PR DESCRIPTION
**Pull request by StephanZimmermann**
heyho kafka-team, please consider our little pull request which adds our use case to your powered-by page. thx

### CODE REVIEW

**Comment by bbejeck** [comment]
Hi @StephanZimmermann if you can rebase this PR we'll get this merged.  Thanks!

**Comment by StephanZimmermann** [comment]
Hi @bbejeck , I did the requested rebase. Ready to pull :-) Cheers

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
@StephanZimmermann thanks for rebasing!

**Pull request merged**
