### PR TITLE
HelloSafe Kafka

### PR DESCRIPTION
**Pull request by SimonRenault86**
HelloSafe is an international online insurance policy comparison platform. It is a completely free site, made available to consumers with the aim of helping them to facilitate their choice of insurance, and to bring more transparency to a market that is often lacking.

### CODE REVIEW

**Review by bbejeck — COMMENTED** [review]
Hi @SimonRenault86, thanks for the PR - can you add  `hellosafe.svg` to the `images/powered-by` directory?

**Comment by SimonRenault86** [comment]
Hello @bbejeck thanks a lot for your feedbacks, i added the picture

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
merged #437 into asf-site

**Comment by bbejeck** [comment]
Thanks @SimonRenault86 for the addition to the Powered By page!

**Pull request merged**
